name: Update Single Page

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update:
    name: Update Single Page
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: python .github/single-page.py
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: .
